int xdelta;
int ydelta;
int xdelta_rot;
int ydelta_rot;
float d0;
float theta_rad;
float theta_full;
float theta_goal;
float theta_goal_rad;
float theta_goal_full;
int w;
int vel;
float delta_angle;
int controller;

int vel_lim = 200;
int distance_threshold = 5;
int angle_threshold = 1;
int k_w = 5;
int k_psi = 5;
int p = 40;
int k_w_g2g = 10;
int k_psi_g2g = 10;
